src/Entity/User.php
<?php

namespace App\Entity;

use App\Enum\ExperienceLevel;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Clock\DatePoint;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['username'], message: 'The username is already in use.')]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank(message: 'Email is required.')]
    #[Assert\Email(message: 'Email is not valid.')]
    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[Assert\NotBlank(message: 'Username is required.')]
    #[Assert\Length(
        min: 3,
        max: 30,
        minMessage: 'Username must be at least {{ limit }} characters',
        maxMessage: 'Username cannot be longer than {{ limit }} characters'
    )]
    #[Assert\Regex(pattern: '/^[a-z0-9_]+$/', message: 'Username can only contain letters, numbers, and underscores.')]
    #[ORM\Column(length: 30, unique: true)]
    private ?string $username = null;

    #[Assert\Length(
        min: 3,
        max: 50,
        minMessage: 'Display name must be at least {{ limit }} characters',
        maxMessage: 'Display name cannot be longer than {{ limit }} characters'
    )]
    #[ORM\Column(length: 50)]
    private ?string $displayName = null;

    #[Assert\Length(
        max: 500,
        maxMessage: 'Bio cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $bio = null;

    #[Assert\Length(
        max: 120,
        maxMessage: 'Location cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 120, nullable: true)]
    private ?string $location = null;

    #[Assert\Url(message: 'Avatar URL is not valid.')]
    #[Assert\Length(
        max: 255,
        maxMessage: 'Image URL cannot be longer than {{ limit }} characters'
    )]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $avatar = null;

    #[Assert\NotBlank(message: 'Experience level is required.')]
    #[ORM\Column(enumType: ExperienceLevel::class)]
    private ?ExperienceLevel $experienceLevel = null;

    #[ORM\Column(type: 'date_point')]
    private ?DatePoint $createdAt = null;

    #[ORM\Column(type: 'date_point')]
    private ?DatePoint $updatedAt = null;

    /**
     * @var Collection<int, Kit>
     */
    #[ORM\OneToMany(targetEntity: Kit::class, mappedBy: 'owner', cascade: ['remove'])]
    private Collection $kits;

    public function __construct()
    {
        $now = new DatePoint();
        $this->createdAt = $now;
        $this->updatedAt = $now;
        $this->kits = new ArrayCollection();
    }

    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        $this->updatedAt = new DatePoint();
    }

    public function isAdmin(): bool
    {
        return in_array('ROLE_ADMIN', $this->roles);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Ensure the session doesn't contain actual password hashes by CRC32C-hashing them, as supported since Symfony 7.3.
     */
    public function __serialize(): array
    {
        $data = (array) $this;
        $data["\0" . self::class . "\0password"] = hash('crc32c', $this->password);

        return $data;
    }

    #[\Deprecated]
    public function eraseCredentials(): void
    {
        // @deprecated, to be removed when upgrading to Symfony 8
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->displayName;
    }

    public function setDisplayName(string $displayName): static
    {
        $this->displayName = $displayName;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): static
    {
        $this->bio = $bio;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): static
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getExperienceLevel(): ?ExperienceLevel
    {
        return $this->experienceLevel;
    }

    public function setExperienceLevel(ExperienceLevel $experienceLevel): static
    {
        $this->experienceLevel = $experienceLevel;

        return $this;
    }

    public function getCreatedAt(): ?DatePoint
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): ?DatePoint
    {
        return $this->updatedAt;
    }

    /**
     * @return Collection<int, Kit>
     */
    public function getKits(): Collection
    {
        return $this->kits;
    }

    public function addKit(Kit $kit): static
    {
        if (!$this->kits->contains($kit)) {
            $this->kits->add($kit);
            $kit->setOwner($this);
        }

        return $this;
    }

    public function removeKit(Kit $kit): static
    {
        if ($this->kits->removeElement($kit)) {
            // set the owning side to null (unless already changed)
            if ($kit->getOwner() === $this) {
                $kit->setOwner(null);
            }
        }

        return $this;
    }
}

src/Form/ItemType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Item;
use App\Form\DataTransformer\JsonTransformer;
use App\Repository\CategoryRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ItemType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        // Need to set model transformer before to avoid symfony form to receive an array instead of a formatted JSON string
        $specs = $builder->create('specifications', TextareaType::class, [
            'label' => 'Specifications (JSON)',
            'attr' => ['class' => 'textarea w-full', 'rows' => 10],
        ]);
        $specs->addModelTransformer(new JsonTransformer());

        $builder
            ->add('name', TextType::class, [
                'attr' => ['class' => 'input w-full'],
            ])
            ->add('brand', TextType::class, [
                'attr' => ['class' => 'input w-full'],
            ])
            ->add('model', TextType::class, [
                'attr' => ['class' => 'input w-full'],
            ])
            ->add('description', TextareaType::class, [
                'required' => false,
                'attr' => ['class' => 'textarea w-full', 'rows' => 5],
            ])
            ->add('imageUrl', UrlType::class, [
                'required' => false,
                'attr' => ['class' => 'input w-full'],
            ])
            ->add($specs)
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => function (Category $category) {
                    return $category->getParent()->getName() . ' - ' . $category->getName();
                },
                'query_builder' => function (CategoryRepository $cr) {
                    return $cr->createQueryBuilder('c')
                        ->andWhere('c.parent IS NOT NULL');
                },
                'attr' => ['class' => 'select w-full'],
            ])
            ->add('itemVariants', CollectionType::class, [
                'entry_type' => ItemVariantType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'prototype_options' => [
                    'attr' => ['class' => 'flex flex-col gap-2'],
                ]
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Item::class,
        ]);
    }
}

src/Controller/ItemController.php
<?php

namespace App\Controller;

use App\Entity\Item;
use App\Entity\ItemVariant;
use App\Enum\ItemStatus;
use App\Form\ItemType;
use App\Repository\ItemRepository;
use App\Repository\KitItemRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/items')]
final class ItemController extends AbstractController
{
    #[IsGranted('IS_AUTHENTICATED')]
    #[Route(name: 'app_item_index', methods: ['GET'])]
    public function index(ItemRepository $itemRepository): Response
    {
        return $this->render('item/index.html.twig', [
            'totalItems' => $itemRepository->countActiveItems()
        ]);
    }

    #[IsGranted('IS_AUTHENTICATED')]
    #[Route('/new', name: 'app_item_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $item = new Item();
        $itemVariant = new ItemVariant();
        $itemVariant->setIsDefault(true);
        $item->addItemVariant($itemVariant);
        $item->setStatus(ItemStatus::PENDING);

        $form = $this->createForm(ItemType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $itemVariant->getName() ?? $itemVariant->setName("Default");

            $item->setCreatedBy($this->getUser());

            $entityManager->persist($item);
            $entityManager->flush();

            return $this->redirectToRoute('app_item_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('item/new.html.twig', [
            'item' => $item,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/suggestions', name: 'app_item_suggestions', methods: ['GET'])]
    public function suggestions(): Response
    {
        return $this->render('item/suggestions.html.twig');
    }

    #[Route('/{id}', name: 'app_item_show', methods: ['GET'])]
    public function show(Item $item): Response
    {
        return $this->render('item/show.html.twig', [
            'item' => $item,
        ]);
    }

    #[IsGranted('ITEM_EDIT', subject: 'item')]
    #[Route('/{id}/edit', name: 'app_item_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Item $item, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ItemType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_item_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('item/edit.html.twig', [
            'item' => $item,
            'form' => $form,
        ]);
    }

    #[IsGranted('ITEM_VALIDATION', subject: 'item')]
    #[Route('/{id}/validate', name: 'app_item_validate', methods: ['GET'])]
    public function validate(Item $item, EntityManagerInterface $entityManager): Response
    {
        $item->setStatus(ItemStatus::VALIDATED);
        $entityManager->flush();

        return $this->redirectToRoute('app_item_show', ['id' => $item->getId()], Response::HTTP_SEE_OTHER);
    }

    #[IsGranted('ITEM_VALIDATION', subject: 'item')]
    #[Route('/{id}/reject', name: 'app_item_reject', methods: ['GET'])]
    public function reject(Item $item, EntityManagerInterface $entityManager, KitItemRepository $kitItemRepository): Response
    {
        $item->setStatus(ItemStatus::REJECTED);
        $entityManager->flush();

        return $this->redirectToRoute('app_item_show', ['id' => $item->getId()], Response::HTTP_SEE_OTHER);
    }

    #[IsGranted('ITEM_DELETE', subject: 'item')]
    #[Route('/{id}', name: 'app_item_delete', methods: ['POST'])]
    public function delete(Request $request, Item $item, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$item->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($item);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_item_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/item/_delete_form.html.twig
<form method="post" action="{{ path('app_item_delete', {'id': item.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ item.id) }}">
    <button class="btn btn-error">Delete</button>
</form>

templates/item/_form.html.twig
{{ form_start(form, {'attr': {'class': 'flex flex-col gap-4 pt-4 lg:mx-auto'}}) }}

<div class="flex flex-col gap-4">
    {{ form_row(form.name, {'row_attr': {'class': 'flex flex-col'}}) }}
    <div class="flex flex-wrap flex-col md:flex-row gap-4 md:items-center">
        {{ form_row(form.brand, {'row_attr': {'class': 'flex flex-col md:flex-1'}}) }}
        {{ form_row(form.model, {'row_attr': {'class': 'flex flex-col md:flex-1'}}) }}
    </div>
    <div class="flex flex-wrap flex-col md:flex-row gap-4">
        {{ form_row(form.category, {'row_attr': {'class': 'flex flex-col flex-1'}}) }}
        {{ form_row(form.imageUrl, {'row_attr': {'class': 'flex flex-col flex-1'}}) }}
    </div>
    {{ form_row(form.description, {'row_attr': {'class': 'flex flex-col'}}) }}
    {{ form_row(form.specifications, {'row_attr': {'class': 'flex flex-col'}}) }}
</div>

<div
    class="flex flex-col gap-4"
    {{ stimulus_controller('form-collection') }}
    data-form-collection-index-value="{{ form.itemVariants|length > 0 ? form.itemVariants|last.vars.name + 1 : 0 }}"
    data-form-collection-prototype-value="{{ form_widget(form.itemVariants.vars.prototype)|e('html_attr') }}"

>
    <div class="sticky top-0 z-10 bg-base-100 p-4 flex items-center justify-between">
        <h3 class="text-lg font-bold">Variants</h3>
        <button type="button" class="btn btn-primary mt-2" id="add-kititem" {{ stimulus_action('form-collection', 'addCollectionElement') }}>Add Item</button>
    </div>
    <div class="collection grid grid-cols-1 lg:grid-cols-2 gap-8" {{ stimulus_target('form-collection', 'collectionContainer') }}>
        {% for variant in form.itemVariants %}
            <div class="flex flex-col gap-2 p-4 bg-base-100 border border-base-300 rounded-field">
                {{ form_widget(variant, {'attr': {'class': 'flex flex-col gap-2'}}) }}
            </div>
        {% endfor %}
    </div>
</div>

{{ form_widget(form) }}

<button type="submit" class="btn btn-success lg:w-50 lg:self-start">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/item/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Item - Edit {{ item.name }}{% endblock %}

{% block body %}
    <h1 class="text-3xl font-bold">Edit Item - {{ item.name }}</h1>
    {{ include('item/_form.html.twig', {'button_label': 'Update'}) }}
    <a class="btn btn-neutral my-4" href="{{ path('app_item_index') }}">Back to list</a>
{% endblock %}

templates/item/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Items{% endblock %}

{% block body %}
    <div class="flex flex-col gap-4">
        <div class="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4 px-4 sm:px-0">
            <h1 class="text-3xl font-bold">My Items</h1>
            <a class="btn btn-outline" href="{{ path('app_item_new') }}">Create New Suggestion</a>
        </div>
        <twig:ItemList currentUser="{{ app.user }}" />
    </div>
{% endblock %}

templates/item/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Item - New{% endblock %}

{% block body %}
    <div>
        <h1 class="text-3xl font-bold">Create new Item</h1>
        <p class="text-base-content/70">Your item will only be available after validation</p>
    </div>
    {{ include('item/_form.html.twig') }}
    <a class="btn btn-neutral my-4" href="{{ path('app_item_index') }}">Back to list</a>
{% endblock %}

templates/item/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Item{% endblock %}

{% block body %}
    <div class="p-6 flex flex-col gap-6">
        <div
            class="card w-full bg-base-100 border border-base-300 overflow-hidden"
        >
            <div class="card-body flex flex-col sm:flex-row gap-4">
                {% if item.imageUrl %}
                    <figure class="max-h-80 overflow-hidden">
                        <img src="{{ item.imageUrl ?? '/images/default-item.png' }}" alt="{{ item.name }}" class="object-fill rounded-box">
                    </figure>
                {% endif %}
                <div class="flex-1 flex flex-col gap-4">
                    <div class="flex items-center justify-between">
                        <h1 class="text-3xl  font-bold text-primary">{{ item.name }}</h1>
                        {% if item.createdBy %}
                            <a href="{{ path('app_item_show', { 'id': item.createdBy.id }) }}" class="avatar tooltip tooltip-bottom" data-tip="{{ item.createdBy.displayName }}">
                                <div class="w-12 rounded-full border border-base-300">
                                    {% if item.createdBy.avatar %}
                                        <img src="{{ item.createdBy.avatar }}" alt="{{ item.createdBy.username }}">
                                    {% else %}
                                        {{ ux_icon('lucide:user-round') }}
                                    {% endif %}
                                </div>
                            </a>
                        {% endif %}
                    </div>
                    <p class="text-neutral text-lg hidden sm:block">{{ item.description }}</p>

                    <div class="flex flex-wrap gap-3 mt-4">
                        <span class="badge badge-secondary gap-1">
                            <i class="iconify" data-icon="{{ item.category.icon ?? 'mdi:package-variant' }}"></i>
                            {{ item.category.name }}
                        </span>
                        <span class="badge {{ item.status.value == 'validated' ? 'badge-success' : item.status.value == 'pending' ? 'badge-info' : 'badge-error'}}">{{ item.status.label }}</span>
            {#  TODO AJOUTER COMME KIT UN CHAMP STATS POUR RECUPERER LES DATAS VARIANTS (RANGE POIDS, PRIX) ??? Variants dispo ... #}
            {#                    <span class="badge badge-outline">Poids: {{ item.weight }} g</span>#}
            {#                    <span class="badge badge-outline">Prix: {{ item.price|number_format(2, '.', ' ') }} €</span>#}
                    </div>
                    <div class="flex flex-col sm:flex-row gap-2 justify-between items-center">
                        <p class="text-base-content/70 text-sm">Updated {{ item.updatedAt|date }}</p>
                        {% if app.user and app.user.admin or item.createdBy == app.user and item.status.value == 'pending' %}
                            <div class="flex items-end gap-2">
                                <a href="{{ path('app_item_edit', {'id': item.id}) }}"
                                   class="btn btn-primary">Edit</a>
                                {{ include('item/_delete_form.html.twig') }}
                            </div>
                        {% endif %}
                        {% if app.user and app.user.admin %}
                            <div class="flex items-end gap-2">
                                <a href="{{ path('app_item_validate', {'id': item.id}) }}" class="btn btn-success">Validate</a>
                                <a href="{{ path('app_item_reject', {'id': item.id}) }}" class="btn btn-error">Reject</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="card w-full bg-base-100 border border-base-300 p-6">
            <h2 class="text-xl font-bold text-primary mb-4">Specifications</h2>
            {% if item.specifications is not empty %}
                <div class="overflow-x-auto">
                    <table class="table table-zebra w-full border-y border-base-300">
                        <tbody>
                        {% for key, value in item.specifications %}
                            <tr>
                                <td class="font-medium capitalize">{{ key|replace({'_':' '})|capitalize }}</td>
                                {% if value is iterable %}
                                    <td>{{ value|map(v => "#{v}")|join(', ') }}</td>
                                {% elseif value is same as(true) or value is same as(false) %}
                                    <td>{{ value ? 'Yes' : 'No' }}</td>
                                {% else %}
                                    <td>{{ value }}</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <p class="text-neutral">No specifications are available yet.</p>
            {% endif %}
        </div>

        <div class="card w-full bg-base-100 border border-base-300 p-6">
            <h2 class="text-xl font-bold text-primary mb-4">Available Variants</h2>
            {% if item.itemVariants is not empty %}
                <div class="grid gap-6 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3">
                    {% for variant in item.itemVariants %}
                        <div class="card bg-base-200/70 border border-base-300 hover:shadow-md transition">
                            <div class="card-body">
                                <h3 class="card-title text-lg text-primary">{{ variant.name }}</h3>
                                <p class="text-sm text-neutral">Weight : {{ variant.weight }} g</p>
                                <p class="text-sm text-neutral">Price : {{ variant.price|number_format(2, '.', ' ') }} €</p>

                                {% if variant.specifications is not empty %}
                                    <div class="mt-3">
                                        <h4 class="font-semibold text-neutral mb-2">Specifications</h4>
                                        <ul class="list-disc list-inside text-sm text-neutral">
                                            {% for key, value in variant.specifications %}
                                                <li>
                                                    <span class="font-medium capitalize">{{ key|replace({'_':' '}) }}</span> :
                                                    {% if value is iterable %}
                                                        {{ value|map(v => "#{v}")|join(', ') }}
                                                    {% else %}
                                                        {{ value }}
                                                    {% endif %}
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p class="text-neutral">No variant available yet.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/item/suggestions.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Items{% endblock %}

{% block body %}
    <div class="flex flex-col gap-4">
        <h1 class="text-3xl font-bold">Suggested Items</h1>
        <twig:ItemList status="pending" :showReset="false" :suggestionPage="true" />
    </div>
{% endblock %}